QCC=fteqcc

all:
	mkdir -p ../../progs/
	$(QCC) $(CFLAGS) -I../../../src/server deathmatch.src
	$(QCC) $(CFLAGS) -I../../../src/server singleplayer.src
	$(QCC) $(CFLAGS) -I../../../src/server invasion.src
